### ISSUE TITLE
Trouble with CDN

### ISSUE THREAD

**Issue by elegault** [OfficeDev/Office-UI-Fabric#241]
I just started playing with Fabric so please excuse any noobness.  But I just cannot figure out why the presence of the NavBar component disables everything on the page.  I have a sample Napa Excel Task Pane app that demonstrates the issue here:

http://aka.ms/V127h2 

I'm properly initializing the component during Office.initialize:

$(".ms-NavBar").NavBar();

I've added a Fabric Button as well just to demonstrate that it gets disabled as well.  If you comment out the entire <div class="ms-NavBar"> block the UI on the page then becomes enabled again (and the Fabric Button is NOT disabled).  I believe something in the /Content/NavBar/Jquery.NavBar.js file is failing or disabling controls but I can't figure out what it is.  Help please!

**Comment by elegault** [comment]
Oops: *If you comment out the entire 'ms-NavBar' div block the UI*...

**Comment by elegault** [comment]
I figured out the problem: for whatever reason referencing the fabric .css files via CDN is not working.  Everything works if I reference the .css files locally.  Shouldn't the CDN reference work though?

**Comment by battletoilet** [comment]
Looking at your application code we noticed a bug in our documentation in how we were referencing the CDN. We just fixed the documentation, can you update your project URL's to the updated path and see if that fixes it? The problem was the link was missing the http: before the CDN Path.

**Comment by elegault** [comment]
It's still not working!

`<link rel="stylesheet" href="http://appsforoffice.microsoft.com/fabric/1.0/fabric.min.css">`
`<link rel="stylesheet" href="http://appsforoffice.microsoft.com/fabric/1.0/fabric.components.min.css">`

**Comment by ericthompson** [comment]
Oh man - that's no good. OK, it seems to work on our end, so there might be something finicky happening with the CDN.

Just to make sure we hone in on the problem, could you hit the URL **http://appsforoffice.microsoft.com/fabric/1.0/fabric.css** in your browser window and see if it brings up the CSS?

**Comment by elegault** [comment]
Yup, I can hit it!  I've updated the sample project: http://aka.ms/V127h2.  You can see how if you remove the comment around the CDN URL in the header (and comment out the local .css refs below it) that it still doesn't work.  What does work with the CDN though is a prompt to display secure content - like it expects an https: reference - but that doesn't work either (although the prompt goes away).

**Comment by ericthompson** [comment]
OK - then this means there is something funky going on with the CDN. We're escalating now - sorry about the inconvenience!

**Comment by elegault** [comment]
Hey no problem, glad I could help

**Comment by ericthompson** [comment]
Hey, @elegault -  could you reset the napa project to have the StartPage be Home.html for us? We want to check through and see what's going wrong. Thanks!

**Comment by elegault** [comment]
Okay, it's been updated

**Comment by ericthompson** [comment]
Awesome - thank you!

**Comment by ericthompson** [comment]
It may seem like we're trying everything, but can you also try referencing the CDN via a http**s** url?

**Comment by mikewheaton** [comment]
Are you still having trouble with the CDN, @elegault?

**Comment by elegault** [comment]
Honestly, I'm not sure which end the problem is on. See issue #251

**Comment by mikewheaton** [comment]
Okay, I'll close this issue for now, as we discuss CDN changes elsewhere and have another one open to troubleshoot your issue.
